name: local_llm
description: "Aplicação desktop nativa para interação com LLMs locais via Ollama."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

# Plataformas suportadas
platforms:
  macos:
  windows:

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  
  # Networking
  dio: ^5.8.0+1
  http: ^1.2.1
  
  # Desktop-specific packages
  window_manager: ^0.4.3
  
  # UI enhancements
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  rive: ^0.13.13
  
  # Theme & UI
  adaptive_theme: ^3.6.0
  
  # Web Scraping & Content Processing
  html: ^0.15.4
  url_launcher: ^6.3.1
  
  # Content Extraction & Parsing
  intl: ^0.19.0                # Internationalization
  csslib: ^1.0.0               # CSS parsing and manipulation
  
  # Advanced HTML parsing
  xml: ^6.5.0                  # XML/HTML parsing
  collection: ^1.18.0          # Advanced collections
  
  # String utilities
  string_similarity: ^2.0.0    # String similarity algorithms
  quiver: ^3.2.1               # Utility functions
  
  # Mathematical operations for scoring
  vector_math: ^2.1.4          # Vector operations for similarity calculations
  
  # Cryptography for cache keys
  crypto: ^3.0.3               # Cryptographic hashing
  
  # Markdown Support  
  markdown_widget: ^2.3.2+6
  flutter_highlight: ^0.7.0
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Icons & UI
  phosphor_flutter: ^2.1.0
  
  # Backend
  langchain_ollama: ^0.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing packages
  mockito: ^5.4.4  
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter
  test: ^1.25.7
  fake_async: ^1.3.1           # Async testing
  http_mock_adapter: ^0.6.1    # HTTP mocking
  mocktail: ^1.0.4             # Advanced mocking
  golden_toolkit: ^0.15.0      # Widget testing

flutter:
  uses-material-design: true
