name: local_llm
description: "Aplicação desktop nativa para interação com LLMs locais via Ollama."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.24.0"

# Plataformas suportadas
platforms:
  macos:
  windows:

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  dio: ^5.8.0+1
  http: ^1.2.1
  
  # Desktop-specific packages
  window_manager: ^0.4.3
  
  # UI enhancements
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  rive: ^0.13.13
  
  # Responsive Layout & UI
  responsive_framework: ^1.5.1
  flutter_staggered_grid_view: ^0.7.0
  adaptive_theme: ^3.6.0
  
  # Platform-specific features
  flutter_haptic: ^0.0.3
  
  # Enhanced Web Scraping
  html: ^0.15.4
  beautiful_soup_dart: ^0.3.0
  xpath_selector_html_parser: ^3.0.1
  url_launcher: ^6.3.1
  
  # Advanced Markdown Support  
  markdown_widget: ^2.3.2+6
  flutter_highlight: ^0.7.0
  code_text_field: ^1.1.0
  syntax_highlight: ^0.2.0
  
  # Enhanced UI Components
  animations: ^2.0.11
  smooth_page_indicator: ^1.2.0+3
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.2
  
  # State Management
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing packages
  mockito: ^5.4.4  
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter
  test: ^1.25.7

flutter:
  uses-material-design: true
