name: Flutter Desktop CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Instala o Flutter (versão estável mais recente)
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Instalar dependências
        run: flutter pub get

      - name: Verificar formatação
        run: flutter format --set-exit-if-changed .

      - name: Analisar código
        run: flutter analyze

      - name: Rodar testes
        run: flutter test
